class SupabaseSecret {
  static const supabaseURL="https://tuoerstrygycaexymbuh.supabase.co";
  static const anonKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1b2Vyc3RyeWd5Y2FleHltYnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTg5ODI3ODksImV4cCI6MjAzNDU1ODc4OX0.Wb-tueIdH6Uhvn8aaOJfr749fywz2F2hL8NeimMICbk";
}